#!/bin/sh

# 
# Copyright © 2015-2021 the original authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      https://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

##############################################################################
# 
#   Gradle start up script for POSIX generated by Gradle.
# 
#   Important for running:
# 
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, e.g.:
#           SHELL=/usr/bin/ksh gradle
# 
#       If you are using a POSIX-compliant shell, you can leave the SHELL
#       environment variable unset.
# 
#   (2) Set the JAVA_HOME environment variable to the absolute path of the
#       Java installation (e.g. /usr/lib/jvm/java-17) used by this Gradle
#       build, else Gradle will report an error saying that a Java 17 (or
#       greater) runtime is not available. If you don't know what your Java
#       installation path is, you can find it by running:
# 
#           echo $JAVA_HOME
# 
#       and if that fails, you can try:
# 
#           /usr/libexec/java_home
# 
#       If you don't have Java installed, you can install it from:
#           https://adoptium.net/
# 
#       If your Java installation is not in a standard location, you can
#       specify the path via the JAVA_HOME environment variable in your
#       shell profile.
# 
#   (3) You also need to set the GRADLE_USER_HOME environment variable to the
#       absolute path of the Gradle user home directory, which is where Gradle
#       stores its compiled scripts, cache, and other data. If you don't set
#       this, Gradle will use your home directory as the Gradle user home,
#       which may cause problems if you have a lot of data there.
# 
#   (4) Make sure to set the GRADLE_OPTS and JAVA_OPTS environment variables
#       to pass JVM arguments to Gradle (e.g. "-Xmx2048m"). You don't need to
#       set them for this particular script, but it's a good practice.
# 
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available file descriptors if possible.
if command -v ulimit > /dev/null 2>&1; then
    ulimit -n 4096 || true
fi

# Make sure to use the absolute path to the Gradle wrapper, not just "gradle".
GRADLE_WRAPPER="$APP_HOME/gradlew"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" ; then
    MAX_FD_LIMIT=$(ulimit -n -H 2>/dev/null) || true
    if [ -n "$MAX_FD_LIMIT" ] && [ "$MAX_FD_LIMIT" -lt 4096 ] ; then
        ulimit -n 4096 || true
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'gradle-launcher-*.jar'

set -- \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs > /dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$XSI_START" "$@"
        printf '%s\n' "$XSI_END"
        xargs -n1 |
        sed ' s~[^[:alnum:],._+=-]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
